"""eht-imaging's polarization conventions, captured as data the notebooks can read.

Notebook 03 claims that its algebra agrees with eht-imaging. That claim is only
worth anything if the notebook actually shows the comparison -- but the notebooks
run in the ``csc494`` environment, which deliberately has no eht-imaging in it, so
importing ``ehtim`` there prints a skip message and proves nothing.

The fix is to commit what eht-imaging says. ``scripts/data/ehtim_pol_conventions.json``
holds the matrices read out of ``ehtim.observing.pol_conventions``, regenerated by
``scripts/export_ehtim_reference.py`` in the ``jax-ehtim`` env. The notebook then
compares against that file, and :func:`check_live` re-does the capture whenever
eht-imaging *is* importable, so a stale file cannot pass unnoticed.

Matrices, not sample values: ``stokes_to_coherency`` and ``coherency_to_stokes``
are linear, so their 4x4 matrices pin the convention for every Stokes vector at
once -- a stronger check than agreeing on one sample sky.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path
from typing import Any

import jones
import numpy as np

#: Where the captured conventions live, relative to ``scripts/``.
REFERENCE_PATH = Path(__file__).parent / "data" / "ehtim_pol_conventions.json"

#: The four feed pairings a two-station baseline can have.
PAIRINGS: tuple[tuple[str, str], ...] = (("rl", "rl"), ("xy", "xy"),
                                         ("xy", "rl"), ("rl", "xy"))

#: Sample gains and D-terms for the ``G (I + D)`` comparison.
SAMPLE_JONES: dict[str, complex] = {"g_p1": 1.2 + 0.1j, "g_p2": 0.85,
                                    "d_p1": 0.04 - 0.01j, "d_p2": -0.02}

#: Two matrices count as agreeing below this, in absolute value.
TOLERANCE = 1e-12


# ---------------------------------------------------------------------------
# JSON encoding: complex arrays as separate real and imaginary parts
# ---------------------------------------------------------------------------

def _encode(array) -> dict[str, Any]:
    values = np.asarray(array, dtype=complex)
    return {"real": values.real.tolist(), "imag": values.imag.tolist()}


def _decode(blob: dict[str, Any]) -> np.ndarray:
    return (np.asarray(blob["real"], dtype=float)
            + 1j * np.asarray(blob["imag"], dtype=float))


# ---------------------------------------------------------------------------
# Capturing and loading
# ---------------------------------------------------------------------------

def capture(pol_conventions) -> dict[str, Any]:
    """Read the conventions out of a live ``pol_conventions`` module.

    Only the matrices: ``export_ehtim_reference.py`` adds the version and date
    when it writes the file.

    Parameters
    ----------
    pol_conventions : module
        ``ehtim.observing.pol_conventions``.

    Returns
    -------
    dict
        JSON-ready: complex arrays split into ``real`` and ``imag`` lists.
    """
    unit = np.eye(4)
    forward, backward = {}, {}
    with warnings.catch_warnings():
        # ehtim warns on every basis change that it assumes ideal feeds. That
        # assumption is exactly what a convention read-out wants.
        warnings.simplefilter("ignore", getattr(
            pol_conventions, "MixedPolConventionWarning", Warning))
        for feed1, feed2 in PAIRINGS:
            key = jones.polbasis(feed1, feed2)
            forward[key] = _encode(np.column_stack([
                pol_conventions.stokes_to_coherency(*stokes, feed1, feed2)
                for stokes in unit]))
            backward[key] = _encode(np.column_stack([
                pol_conventions.coherency_to_stokes(*slots, feed1, feed2)
                for slots in unit]))

    return {
        "feed_matrix": {feed_type: _encode(pol_conventions.feed_matrix(feed_type))
                        for feed_type in jones.FEED_TYPES},
        "stokes_to_slots": forward,
        "slots_to_stokes": backward,
        "jones_matrix": _encode(pol_conventions.jones_matrix(*SAMPLE_JONES.values())),
    }


def load(path: Path | str = REFERENCE_PATH) -> dict[str, Any]:
    """Load the committed capture, decoding its matrices to complex arrays."""
    with open(path) as handle:
        stored = json.load(handle)
    return {
        "ehtim_version": stored["ehtim_version"],
        "ehtim_module": stored["ehtim_module"],
        "captured": stored["captured"],
        "feed_matrix": {key: _decode(value)
                        for key, value in stored["feed_matrix"].items()},
        "stokes_to_slots": {key: _decode(value)
                            for key, value in stored["stokes_to_slots"].items()},
        "slots_to_stokes": {key: _decode(value)
                            for key, value in stored["slots_to_stokes"].items()},
        "jones_matrix": _decode(stored["jones_matrix"]),
    }


# ---------------------------------------------------------------------------
# The comparison itself
# ---------------------------------------------------------------------------

def comparisons(reference: dict[str, Any] | None = None
                ) -> list[tuple[str, float]]:
    """Compare ``jones.py`` against the captured conventions, term by term.

    Returns
    -------
    list of (str, float)
        A label and the largest absolute difference, for each of eleven
        quantities: the two feed matrices, both directions of the 4x4 Stokes
        conversion for all four feed pairings, and ``G (I + D)``.
    """
    if reference is None:
        reference = load()

    rows: list[tuple[str, float]] = []

    def add(label: str, mine, theirs) -> None:
        rows.append((label, float(np.abs(np.asarray(mine)
                                         - np.asarray(theirs)).max())))

    for feed_type in jones.FEED_TYPES:
        add(f"feed matrix {feed_type.upper()}",
            jones.feed_matrix(feed_type), reference["feed_matrix"][feed_type])

    unit = np.eye(4)
    for feed1, feed2 in PAIRINGS:
        key = jones.polbasis(feed1, feed2)
        pairing = f"{feed1.upper()}×{feed2.upper()}"
        add(f"Stokes → slots, {pairing}",
            np.column_stack([jones.slots_from_stokes(stokes, feed1, feed2)
                             for stokes in unit]),
            reference["stokes_to_slots"][key])
        add(f"slots → Stokes, {pairing}",
            jones.slots_to_stokes_matrix(feed1, feed2),
            reference["slots_to_stokes"][key])

    add("G · (I + D)",
        jones.gain_matrix(SAMPLE_JONES["g_p1"], SAMPLE_JONES["g_p2"])
        @ jones.dterm_matrix(SAMPLE_JONES["d_p1"], SAMPLE_JONES["d_p2"]),
        reference["jones_matrix"])

    return rows


def check_live(reference: dict[str, Any] | None = None) -> str:
    """Re-capture from an installed eht-imaging, if there is one, and compare.

    Returns
    -------
    str
        One line for the notebook: whether the committed file still matches the
        installed eht-imaging, or that eht-imaging is absent here.
    """
    if reference is None:
        reference = load()
    try:
        import ehtim
        from ehtim.observing import pol_conventions
    except ImportError:
        return ("eht-imaging is not installed in this environment, so the "
                "comparison above uses the committed capture; "
                "scripts/tests/test_ehtim_reference.py redoes it against the "
                "live module wherever there is one.")

    fresh = capture(pol_conventions)
    error = max(
        float(np.abs(_decode(fresh[section][key])
                     - reference[section][key]).max())
        for section in ("feed_matrix", "stokes_to_slots", "slots_to_stokes")
        for key in fresh[section]
    )
    error = max(error, float(np.abs(_decode(fresh["jones_matrix"])
                                    - reference["jones_matrix"]).max()))
    verdict = "still matches" if error < TOLERANCE else "NO LONGER MATCHES"
    return (f"eht-imaging v{ehtim.__version__} is importable here: "
            f"the committed capture {verdict} it (max difference {error:.1e}).")
